In [1]:
import keras

Using Theano backend.


In [2]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD, Adam, RMSprop
from keras.utils import np_utils

In [3]:
from keras.layers.advanced_activations import LeakyReLU
from custom_activations import funky

In [4]:
act1 = LeakyReLU()

In [5]:
act2 = funky()

In [6]:
model = Sequential()
model.add(Dense(128, input_shape=(784,)))
model.add(Activation(act1))
model.add(Dense(10))
model.add(Activation('softmax'))
sgd = SGD()

In [7]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
#print(X_train.shape[0], 'train samples')
#print(X_test.shape[0], 'test samples')

#convert class vectors to binary class matrices
nb_classes = 10
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

In [8]:
%time model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])

CPU times: user 16 ms, sys: 2.31 ms, total: 18.3 ms
Wall time: 17.2 ms


In [9]:
h = model.fit(X_train, Y_train, batch_size =128, nb_epoch=3, show_accuracy = True, validation_data = (X_test, Y_test), verbose=1)

/Users/trishala/anaconda2/envs/newkeras/lib/python2.7/site-packages/keras/models.py:603: UserWarning: The "show_accuracy" argument is deprecated, instead you should pass the "accuracy" metric to the model at compile time:
`model.compile(optimizer, loss, metrics=["accuracy"])`
  warnings.warn('The "show_accuracy" argument is deprecated, '


Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 1s - loss: 0.3551 - acc: 0.9002 - val_loss: 0.2211 - val_acc: 0.9378
Epoch 2/3
60000/60000 [==============================] - 2s - loss: 0.2070 - acc: 0.9407 - val_loss: 0.1911 - val_acc: 0.9423
Epoch 3/3
60000/60000 [==============================] - 2s - loss: 0.1634 - acc: 0.9525 - val_loss: 0.1536 - val_acc: 0.9572


In [10]:
W1,b1,W2,b2 = model.get_weights()

In [11]:
W1

array([[ 0.01600214, -0.07801446, -0.07119832, ..., -0.041309  ,
         0.07803798, -0.05080473],
       [ 0.01212427, -0.05693202,  0.00829877, ...,  0.01097088,
        -0.01218118, -0.00358188],
       [-0.02798825,  0.06245501,  0.04549764, ..., -0.05590139,
         0.04120227,  0.065405  ],
       ..., 
       [ 0.0337082 , -0.07150807,  0.07356078, ...,  0.06233416,
         0.02434243,  0.07402773],
       [-0.0600154 , -0.0706914 , -0.07367878, ..., -0.05974371,
        -0.05202013,  0.02022146],
       [ 0.04259464,  0.03292132,  0.0536679 , ..., -0.01986279,
        -0.06798334, -0.06073821]], dtype=float32)

In [12]:
b1

array([ 0.00825811,  0.07034484,  0.04879795, -0.07672587,  0.0935107 ,
        0.01884316,  0.00590938,  0.08231358, -0.05029014,  0.05958919,
        0.00149697, -0.01409578, -0.00522174, -0.01034627,  0.03978691,
        0.06542351,  0.00137629,  0.05210906,  0.00375271,  0.05021174,
        0.0553347 ,  0.02844198, -0.06818917,  0.0094202 , -0.01213054,
        0.06961968,  0.08191475, -0.04527924,  0.09312265, -0.01524968,
        0.02830494, -0.01926779,  0.09389703, -0.01289984,  0.12041978,
       -0.04631449,  0.13182391,  0.08095248, -0.02886299, -0.0544009 ,
        0.00996719, -0.06426766,  0.08472405,  0.02610137,  0.09607317,
       -0.01284796, -0.05732202,  0.13661037, -0.01024327, -0.03598059,
       -0.06330252,  0.03495168,  0.17538677,  0.05476326,  0.06474174,
        0.09857379, -0.10356673,  0.08916046,  0.08619529,  0.10525808,
        0.11103232, -0.02014363,  0.05625378,  0.01379062,  0.02381451,
        0.03919306,  0.03861884,  0.05550249,  0.01296674, -0.01

In [13]:
W2

array([[-0.34696746,  0.05446142,  0.05927617, ..., -0.16751352,
        -0.08544301, -0.17020532],
       [-0.18250924, -0.17484649,  0.07183832, ...,  0.17819972,
        -0.29421961, -0.45739144],
       [-0.03661508, -0.14699148,  0.20060135, ...,  0.03836012,
        -0.2201346 , -0.44855061],
       ..., 
       [ 0.14999257, -0.18660249,  0.02031232, ..., -0.0793832 ,
         0.14349464,  0.0257253 ],
       [ 0.24570411, -0.21398783,  0.04488847, ..., -0.11503445,
        -0.40964434, -0.28187802],
       [ 0.17716143,  0.11679867,  0.09549677, ..., -0.35319227,
         0.19845247, -0.26310661]], dtype=float32)

In [14]:
b2

array([-0.07976025,  0.04977971,  0.03185508, -0.03306931, -0.01756616,
        0.11599142, -0.05018019,  0.06253695, -0.06383394, -0.01671107], dtype=float32)

In [15]:
model.add(Activation(act2))

In [16]:
%time model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])
#compiles Faster

CPU times: user 13.2 ms, sys: 2.55 ms, total: 15.8 ms
Wall time: 14 ms


In [17]:
h = model.fit(X_train, Y_train, batch_size =128, nb_epoch=3, show_accuracy = True, validation_data = (X_test, Y_test), verbose=1)
#Higher accuracy

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 2s - loss: 0.1368 - acc: 0.9610 - val_loss: 0.1352 - val_acc: 0.9615
Epoch 2/3
60000/60000 [==============================] - 2s - loss: 0.1159 - acc: 0.9661 - val_loss: 0.1265 - val_acc: 0.9614
Epoch 3/3
60000/60000 [==============================] - 2s - loss: 0.1017 - acc: 0.9708 - val_loss: 0.1097 - val_acc: 0.9670


In [18]:
W1

array([[ 0.01600214, -0.07801446, -0.07119832, ..., -0.041309  ,
         0.07803798, -0.05080473],
       [ 0.01212427, -0.05693202,  0.00829877, ...,  0.01097088,
        -0.01218118, -0.00358188],
       [-0.02798825,  0.06245501,  0.04549764, ..., -0.05590139,
         0.04120227,  0.065405  ],
       ..., 
       [ 0.0337082 , -0.07150807,  0.07356078, ...,  0.06233416,
         0.02434243,  0.07402773],
       [-0.0600154 , -0.0706914 , -0.07367878, ..., -0.05974371,
        -0.05202013,  0.02022146],
       [ 0.04259464,  0.03292132,  0.0536679 , ..., -0.01986279,
        -0.06798334, -0.06073821]], dtype=float32)

In [19]:
b1

array([ 0.00825811,  0.07034484,  0.04879795, -0.07672587,  0.0935107 ,
        0.01884316,  0.00590938,  0.08231358, -0.05029014,  0.05958919,
        0.00149697, -0.01409578, -0.00522174, -0.01034627,  0.03978691,
        0.06542351,  0.00137629,  0.05210906,  0.00375271,  0.05021174,
        0.0553347 ,  0.02844198, -0.06818917,  0.0094202 , -0.01213054,
        0.06961968,  0.08191475, -0.04527924,  0.09312265, -0.01524968,
        0.02830494, -0.01926779,  0.09389703, -0.01289984,  0.12041978,
       -0.04631449,  0.13182391,  0.08095248, -0.02886299, -0.0544009 ,
        0.00996719, -0.06426766,  0.08472405,  0.02610137,  0.09607317,
       -0.01284796, -0.05732202,  0.13661037, -0.01024327, -0.03598059,
       -0.06330252,  0.03495168,  0.17538677,  0.05476326,  0.06474174,
        0.09857379, -0.10356673,  0.08916046,  0.08619529,  0.10525808,
        0.11103232, -0.02014363,  0.05625378,  0.01379062,  0.02381451,
        0.03919306,  0.03861884,  0.05550249,  0.01296674, -0.01

In [20]:
W2

array([[-0.34696746,  0.05446142,  0.05927617, ..., -0.16751352,
        -0.08544301, -0.17020532],
       [-0.18250924, -0.17484649,  0.07183832, ...,  0.17819972,
        -0.29421961, -0.45739144],
       [-0.03661508, -0.14699148,  0.20060135, ...,  0.03836012,
        -0.2201346 , -0.44855061],
       ..., 
       [ 0.14999257, -0.18660249,  0.02031232, ..., -0.0793832 ,
         0.14349464,  0.0257253 ],
       [ 0.24570411, -0.21398783,  0.04488847, ..., -0.11503445,
        -0.40964434, -0.28187802],
       [ 0.17716143,  0.11679867,  0.09549677, ..., -0.35319227,
         0.19845247, -0.26310661]], dtype=float32)

In [21]:
b2

array([-0.07976025,  0.04977971,  0.03185508, -0.03306931, -0.01756616,
        0.11599142, -0.05018019,  0.06253695, -0.06383394, -0.01671107], dtype=float32)