In [1]:
import keras

Using Theano backend.


In [2]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD, Adam, RMSprop
from keras.utils import np_utils

In [3]:
from keras.layers.advanced_activations import LeakyReLU
from custom_activations import funky

In [4]:
act1 = LeakyReLU()

In [5]:
act2 = funky()

In [6]:
model = Sequential()
model.add(Dense(128, input_shape=(784,)))
model.add(Activation(act2))
model.add(Dense(10))
model.add(Activation('softmax'))
sgd = SGD()

In [7]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
#print(X_train.shape[0], 'train samples')
#print(X_test.shape[0], 'test samples')

#convert class vectors to binary class matrices
nb_classes = 10
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

In [8]:
%time model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])

CPU times: user 20.4 ms, sys: 2.55 ms, total: 23 ms
Wall time: 40.5 ms


In [9]:
h = model.fit(X_train, Y_train, batch_size =128, nb_epoch=3, show_accuracy = True, validation_data = (X_test, Y_test), verbose=1)

/Users/trishala/anaconda2/envs/newkeras/lib/python2.7/site-packages/keras/models.py:603: UserWarning: The "show_accuracy" argument is deprecated, instead you should pass the "accuracy" metric to the model at compile time:
`model.compile(optimizer, loss, metrics=["accuracy"])`
  warnings.warn('The "show_accuracy" argument is deprecated, '


Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 1s - loss: 0.3898 - acc: 0.8905 - val_loss: 0.2856 - val_acc: 0.9207
Epoch 2/3
60000/60000 [==============================] - 2s - loss: 0.2936 - acc: 0.9177 - val_loss: 0.2842 - val_acc: 0.9203
Epoch 3/3
60000/60000 [==============================] - 2s - loss: 0.2827 - acc: 0.9212 - val_loss: 0.2852 - val_acc: 0.9216


In [10]:
W1,b1,W2,b2 = model.get_weights()

In [11]:
W1

array([[-0.04392318, -0.00940219,  0.00223801, ..., -0.02793726,
         0.03599655,  0.02997522],
       [ 0.07272904,  0.04198454, -0.03632539, ...,  0.07772131,
        -0.01769266, -0.00653781],
       [ 0.06548129,  0.01637574,  0.02380114, ..., -0.0034843 ,
        -0.01144139, -0.03988527],
       ..., 
       [ 0.00863879, -0.07043242, -0.04175187, ..., -0.02681349,
         0.00364234, -0.0023927 ],
       [ 0.05215555,  0.01604078,  0.05344005, ...,  0.05476426,
        -0.0539187 ,  0.01760176],
       [-0.07785074, -0.04327604, -0.02975892, ...,  0.01032834,
         0.07638571,  0.02024396]], dtype=float32)

In [12]:
b1

array([-0.19732136,  0.09122638,  0.11815937,  0.12480889, -0.15667067,
        0.03988222, -0.0213027 , -0.05312961, -0.01030233,  0.04201516,
       -0.0474821 , -0.12024364,  0.0600786 ,  0.10486793, -0.09157707,
        0.13355842, -0.00673402,  0.20884708,  0.04053801, -0.1286813 ,
        0.12574254, -0.19018535,  0.06731959, -0.16640234, -0.08561629,
        0.11659639, -0.15480274, -0.13791181,  0.02459438,  0.1886773 ,
       -0.01033094,  0.01034829,  0.11090334,  0.01742894, -0.07982948,
       -0.01224479,  0.0996527 ,  0.10432689, -0.08288068, -0.01186527,
        0.05665839,  0.0695508 ,  0.14125046, -0.0118904 ,  0.14133494,
       -0.00540399,  0.09333972,  0.07497164,  0.11954736,  0.20957442,
        0.05800946,  0.14161263,  0.10682194, -0.01973605, -0.09013104,
        0.03666779,  0.12867579,  0.01839055,  0.1316388 , -0.02107663,
        0.05146091, -0.18161705, -0.07549278, -0.16062488, -0.07717127,
       -0.0355635 ,  0.05351952,  0.20311132, -0.05947957, -0.18

In [13]:
W2

array([[-0.10714442, -0.17105585,  0.1357511 , ..., -0.12533577,
         0.08425178, -0.03861317],
       [-0.15053828,  0.21258156,  0.12363887, ...,  0.06113201,
         0.0886974 , -0.01077479],
       [ 0.13035604,  0.17727835,  0.05204573, ...,  0.18832876,
         0.01604614, -0.18736075],
       ..., 
       [ 0.10027292,  0.29947025,  0.17692792, ...,  0.25682381,
        -0.12260468,  0.17760749],
       [-0.00824683, -0.1351162 , -0.22955708, ..., -0.22301453,
         0.15705812,  0.0706014 ],
       [-0.06097505,  0.23152465, -0.12275994, ...,  0.04931208,
        -0.00270012, -0.0443862 ]], dtype=float32)

In [14]:
b2

array([-0.08753993,  0.06722572,  0.051009  , -0.0556617 ,  0.02366049,
        0.20501067, -0.03554799,  0.08555239, -0.18353893, -0.03802162], dtype=float32)

In [16]:
act2.name #why funky_1?

'funky_1'