In [1]:
import keras

Using Theano backend.


In [2]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD, Adam, RMSprop
from keras.utils import np_utils

In [3]:
from keras.layers.advanced_activations import LeakyReLU
from custom_activations import funky

In [4]:
act1 = LeakyReLU()

In [5]:
act2 = funky()

In [6]:
model = Sequential()
model.add(Dense(128, input_shape=(784,)))
model.add(Activation(act2))
model.add(Dense(10))
model.add(Activation('softmax'))
sgd = SGD()

In [7]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
#print(X_train.shape[0], 'train samples')
#print(X_test.shape[0], 'test samples')

#convert class vectors to binary class matrices
nb_classes = 10
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

In [8]:
%time model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])

#Faster! But similar accuracies

CPU times: user 12.9 ms, sys: 2.02 ms, total: 14.9 ms
Wall time: 14.4 ms


In [9]:
h = model.fit(X_train, Y_train, batch_size =128, nb_epoch=3, show_accuracy = True, validation_data = (X_test, Y_test), verbose=1)

/Users/trishala/anaconda2/envs/newkeras/lib/python2.7/site-packages/keras/models.py:603: UserWarning: The "show_accuracy" argument is deprecated, instead you should pass the "accuracy" metric to the model at compile time:
`model.compile(optimizer, loss, metrics=["accuracy"])`
  warnings.warn('The "show_accuracy" argument is deprecated, '


Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 1s - loss: 0.3866 - acc: 0.8914 - val_loss: 0.2995 - val_acc: 0.9153
Epoch 2/3
60000/60000 [==============================] - 2s - loss: 0.2942 - acc: 0.9171 - val_loss: 0.2923 - val_acc: 0.9187
Epoch 3/3
60000/60000 [==============================] - 2s - loss: 0.2837 - acc: 0.9205 - val_loss: 0.2917 - val_acc: 0.9172


In [10]:
W1,b1,W2,b2 = model.get_weights()

In [11]:
W1

array([[-0.01411955, -0.02707999, -0.01429438, ...,  0.04370084,
         0.04148508, -0.01531713],
       [ 0.03839912,  0.05203186, -0.04816595, ...,  0.03878478,
         0.02930572, -0.03676845],
       [ 0.01205098,  0.06417956,  0.04291197, ..., -0.00728522,
         0.00392917, -0.0153737 ],
       ..., 
       [ 0.01906013,  0.05517058,  0.07970759, ..., -0.02341249,
         0.01176584, -0.07189351],
       [ 0.04002133,  0.02966335, -0.02059489, ...,  0.05221587,
        -0.02323005, -0.04197509],
       [-0.03849692, -0.07032873,  0.02812876, ...,  0.03593689,
         0.05946992,  0.00061742]], dtype=float32)

In [12]:
b1

array([-0.0261254 ,  0.07056863,  0.01571248, -0.17559284,  0.09135401,
       -0.19134818,  0.15001026,  0.11207247, -0.1018461 ,  0.00987686,
        0.00070437,  0.08858409,  0.00926275,  0.1961588 , -0.1451423 ,
       -0.03971472,  0.1771263 ,  0.02292113, -0.08534971, -0.11919432,
        0.11157175, -0.07347897,  0.10584903, -0.07915641, -0.0291166 ,
        0.17708397, -0.02045507, -0.10346566,  0.00316526, -0.08067903,
        0.1503755 , -0.12885685,  0.11294539,  0.01151587,  0.09151273,
        0.01213997, -0.05777294,  0.070219  ,  0.00815507,  0.1229982 ,
       -0.04614078,  0.144227  ,  0.13643719, -0.01235144, -0.09605792,
        0.03942292, -0.1182886 , -0.10661017,  0.08606984, -0.10542819,
       -0.0902491 ,  0.17502137, -0.066681  ,  0.13783252,  0.11874145,
       -0.0818641 , -0.00827882,  0.0778539 ,  0.03667735,  0.13007115,
        0.16884667, -0.11590551,  0.08952458, -0.09187032, -0.02428015,
        0.05049475, -0.04182416, -0.24571392, -0.01195023,  0.09

In [13]:
W2

array([[-0.12847827,  0.29370278, -0.08351583, ..., -0.02987729,
        -0.0880971 , -0.22596164],
       [-0.13654025, -0.035915  ,  0.12409417, ...,  0.11701564,
        -0.17964108,  0.1287232 ],
       [ 0.24820694, -0.14187121,  0.02569423, ..., -0.11094671,
        -0.11373036,  0.04288781],
       ..., 
       [-0.03775074,  0.20828493, -0.12403846, ...,  0.05365087,
         0.14120229,  0.04952286],
       [ 0.15462986, -0.02247178,  0.19852148, ..., -0.05360553,
         0.12691095, -0.15063755],
       [ 0.058429  ,  0.25508288,  0.16190569, ...,  0.12703905,
         0.0633273 ,  0.04791488]], dtype=float32)

In [14]:
b2

array([-0.0935614 ,  0.07063937,  0.04238594, -0.05118836,  0.02522801,
        0.192449  , -0.0407309 ,  0.09841862, -0.17750598, -0.03880737], dtype=float32)

In [15]:
act2.name #why funky_1?

'funky_1'

In [16]:
#Not coding his attempt of using math...

In [17]:
# error: float requires